"""Workspace management for code generation."""

import shutil
import subprocess
from pathlib import Path
from typing import Optional, Dict


class WorkspaceManager:
    """Manages workspaces for agent code generation.

    Each sprint gets its own workspace directory with git initialized.
    Supports cloning from remote repos or starting fresh.
    """

    def __init__(self, base_dir: str, repo_config: Optional[Dict] = None):
        """Initialize workspace manager.

        Args:
            base_dir: Base directory for all workspaces (e.g., /tmp/agent-workspace)
            repo_config: Optional config for cloning existing repos
                {
                    "url": "https://github.com/org/project.git",
                    "branch": "main",
                    "clone_mode": "fresh" | "incremental"
                }
        """
        self.base_dir = Path(base_dir)
        self.repo_config = repo_config or {}
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def create_sprint_workspace(self, sprint_num: int, story_id: str = None) -> Path:
        """Create a workspace for a sprint with feature branch.

        Follows stable main + gitflow:
        1. Initialize/clone repo
        2. Create feature branch for story: feature/<story-id>

        Args:
            sprint_num: Sprint number
            story_id: Optional story ID for sub-workspace

        Returns:
            Path to the workspace directory
        """
        if story_id:
            workspace = self.base_dir / f"sprint-{sprint_num}" / story_id
        else:
            workspace = self.base_dir / f"sprint-{sprint_num}"

        # Create fresh workspace
        if workspace.exists():
            shutil.rmtree(workspace)

        workspace.mkdir(parents=True, exist_ok=True)

        # Initialize or clone
        if self.repo_config.get("url"):
            self._clone_repo(workspace)
        else:
            self._init_fresh_repo(workspace)

        # Create feature branch if story_id provided
        if story_id:
            self.create_feature_branch(workspace, story_id)

        return workspace

    def _init_fresh_repo(self, workspace: Path):
        """Initialize a fresh git repo in the workspace."""
        subprocess.run(
            ["git", "init"],
            cwd=workspace,
            capture_output=True,
            check=True
        )

        subprocess.run(
            ["git", "config", "user.name", "Agile Agent Team"],
            cwd=workspace,
            capture_output=True,
            check=True
        )

        subprocess.run(
            ["git", "config", "user.email", "agents@example.com"],
            cwd=workspace,
            capture_output=True,
            check=True
        )

        # Create initial commit
        readme = workspace / "README.md"
        readme.write_text("# Project\n\nGenerated by Agile Agent Team\n")

        subprocess.run(["git", "add", "README.md"], cwd=workspace, capture_output=True, check=True)
        subprocess.run(
            ["git", "commit", "-m", "Initial commit"],
            cwd=workspace,
            capture_output=True,
            check=True
        )

    def _clone_repo(self, workspace: Path):
        """Clone a repo into the workspace."""
        url = self.repo_config["url"]
        branch = self.repo_config.get("branch", "main")

        subprocess.run(
            ["git", "clone", "--branch", branch, "--depth", "1", url, str(workspace)],
            capture_output=True,
            check=True
        )

    def create_feature_branch(self, workspace: Path, story_id: str) -> str:
        """Create a feature branch for a story.

        Args:
            workspace: Workspace directory
            story_id: Story ID (e.g., "US-001")

        Returns:
            Branch name created
        """
        branch_name = f"feature/{story_id.lower()}"

        subprocess.run(
            ["git", "checkout", "-b", branch_name],
            cwd=workspace,
            capture_output=True,
            check=True
        )

        return branch_name

    def get_workspace_for_sprint(self, sprint_num: int) -> Optional[Path]:
        """Get existing workspace for a sprint if it exists."""
        workspace = self.base_dir / f"sprint-{sprint_num}"
        return workspace if workspace.exists() else None

    def cleanup_old_workspaces(self, keep_last_n: int = 3):
        """Clean up old sprint workspaces, keeping only the last N."""
        sprint_dirs = sorted(
            [d for d in self.base_dir.glob("sprint-*") if d.is_dir()],
            key=lambda p: int(p.name.split("-")[1]),
            reverse=True
        )

        for old_dir in sprint_dirs[keep_last_n:]:
            shutil.rmtree(old_dir)
